# Generated by Django 6.0.7 on 2026-07-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churches',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churches',
            name='pastor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churches',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
