# Generated by Django 6.0.7 on 2026-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_churches_address_alter_churches_pastor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
