# Generated by Django 6.0.7 on 2026-07-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_members_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='church_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.churches'),
        ),
    ]
