# Generated by Django 6.0.7 on 2026-07-24 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_members_church_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='church',
        ),
        migrations.AlterField(
            model_name='members',
            name='church_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.churches'),
        ),
    ]
