services:
  - type: web
    name: church-donation-backend
    runtime: python
    # Tells Render to scope all paths inside the backend subfolder
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn church_donation_management.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: church-donation-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: church-donation-db
    plan: free
